import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 10, fontFamily: 'Helvetica' },
  header: { textAlign: 'center', marginBottom: 20, borderBottom: '2px solid #ff6b00', paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: 'bold', color: '#ff6b00' },
  subtitle: { fontSize: 10, color: '#666', marginTop: 4 },
  summary: { marginBottom: 15, padding: 10, backgroundColor: '#f9f9ff', borderRadius: 4 },
  table: { marginTop: 10 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 6, borderBottom: '1px solid #ddd' },
  tableRow: { flexDirection: 'row', padding: 6, borderBottom: '1px solid #eee' },
  colName: { width: '20%' },
  colNik: { width: '15%' },
  colDept: { width: '18%' },
  colPos: { width: '17%' },
  colRight: { width: '15%', textAlign: 'right' },
  colStatus: { width: '15%' },
  footer: { marginTop: 20, textAlign: 'center', fontSize: 8, color: '#999' }
});

const formatRupiahPDF = (val) => {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(val || 0);
};

const EmployeeReportPDF = ({ data }) => (
  <Document>
    <Page size="A4" orientation="landscape" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>PAYLOCITY</Text>
        <Text style={styles.subtitle}>Laporan Data Karyawan</Text>
      </View>

      <View style={styles.summary}>
        <Text>Total Karyawan: {data.summary.totalEmployees}</Text>
      </View>

      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.colName}>Nama</Text>
          <Text style={styles.colNik}>NIK</Text>
          <Text style={styles.colDept}>Departemen</Text>
          <Text style={styles.colPos}>Jabatan</Text>
          <Text style={styles.colRight}>Gaji Pokok</Text>
          <Text style={styles.colStatus}>Status</Text>
        </View>
        {data.details.map((row, i) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.colName}>{row.name}</Text>
            <Text style={styles.colNik}>{row.nik}</Text>
            <Text style={styles.colDept}>{row.department}</Text>
            <Text style={styles.colPos}>{row.position}</Text>
            <Text style={styles.colRight}>{formatRupiahPDF(row.basicSalary)}</Text>
            <Text style={styles.colStatus}>{row.status}</Text>
          </View>
        ))}
      </View>

      <View style={styles.footer}>
        <Text>Generated by Paylocity HRIS System</Text>
      </View>
    </Page>
  </Document>
);

export default EmployeeReportPDF;