import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 10, fontFamily: 'Helvetica' },
  header: { textAlign: 'center', marginBottom: 20, borderBottom: '2px solid #ff6b00', paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: 'bold', color: '#ff6b00' },
  subtitle: { fontSize: 10, color: '#666', marginTop: 4 },
  summary: { marginBottom: 15, padding: 10, backgroundColor: '#f9f9ff', borderRadius: 4 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  table: { marginTop: 10 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 6, borderBottom: '1px solid #ddd' },
  tableRow: { flexDirection: 'row', padding: 6, borderBottom: '1px solid #eee' },
  colName: { width: '18%' },
  colDate: { width: '12%' },
  colTime: { width: '15%' },
  colHours: { width: '10%' },
  colType: { width: '12%' },
  colStatus: { width: '12%' },
  colRight: { width: '12%', textAlign: 'right' },
  footer: { marginTop: 20, textAlign: 'center', fontSize: 8, color: '#999' }
});

const formatRupiahPDF = (val) => {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(val || 0);
};

const formatDatePDF = (val) => {
  if (!val) return '-';
  return new Date(val).toLocaleDateString('id-ID');
};

const OvertimeReportPDF = ({ data }) => (
  <Document>
    <Page size="A4" orientation="landscape" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>PAYLOCITY</Text>
        <Text style={styles.subtitle}>Laporan Lembur Periode {data.period}</Text>
      </View>

      <View style={styles.summary}>
        <View style={styles.summaryRow}>
          <Text>Total Pengajuan: {data.summary.totalRequests}</Text>
          <Text>Jam Approved: {data.summary.totalApprovedHours.toFixed(2)}</Text>
          <Text>Biaya Approved: {formatRupiahPDF(data.summary.totalApprovedCost)}</Text>
        </View>
        <View style={styles.summaryRow}>
          <Text>Pending: {data.summary.countByStatus.PENDING || 0}</Text>
          <Text>Approved: {data.summary.countByStatus.APPROVED || 0}</Text>
          <Text>Rejected: {data.summary.countByStatus.REJECTED || 0}</Text>
        </View>
      </View>

      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.colName}>Nama</Text>
          <Text style={styles.colDate}>Tanggal</Text>
          <Text style={styles.colTime}>Jam</Text>
          <Text style={styles.colHours}>Total Jam</Text>
          <Text style={styles.colType}>Jenis</Text>
          <Text style={styles.colStatus}>Status</Text>
          <Text style={styles.colRight}>Biaya</Text>
        </View>
        {data.details.map((row, i) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.colName}>{row.name}</Text>
            <Text style={styles.colDate}>{formatDatePDF(row.date)}</Text>
            <Text style={styles.colTime}>{row.startTime} - {row.endTime}</Text>
            <Text style={styles.colHours}>{row.totalHours}</Text>
            <Text style={styles.colType}>{row.dayType === 'WEEKDAY' ? 'Hari Kerja' : 'Hari Libur'}</Text>
            <Text style={styles.colStatus}>{row.status}</Text>
            <Text style={styles.colRight}>{formatRupiahPDF(row.overtimePay)}</Text>
          </View>
        ))}
      </View>

      <View style={styles.footer}>
        <Text>Generated by Paylocity HRIS System</Text>
      </View>
    </Page>
  </Document>
);

export default OvertimeReportPDF;